### ISSUE TITLE
TODO List before release of beta version.

### ISSUE THREAD

**Issue by khalibartan** [AntidoteLabs/Antidote-DM#4]
- [ ] Rewriting the base graphics of Antidote-dm 
- [ ] Rewriting Ebook search because library genesis have changed their api.
- [ ] Searching movies directly from gen videos
- [ ] Pause functionality
- [ ] Building cache for previous searches and downloads.
- [ ] Multi-threading for download boosting (optional)
- [ ] Direct music search (suggest sites)
- [ ] Support like coursera-dl in terms of searching, login, downloading  
- [ ] Support like youtube-dl in terms of searching, login, downloading

**Comment by khalibartan** [comment]
@pdoongarwal Add other features to the list you find relevant.
We can use the existing code of youtube-dl and coursera-dl and customize it according to our needs. I think it is better to use there code because we cannot update things as regularly as these packages.
Also you can should take a look at this repo
https://github.com/yask123/Instant-Music-Downloader
I think we can add support like this in our software too.

**Comment by khalibartan** [comment]
@pdoongarwal 
I think we should use kivy for our graphics maybe. Don't know whether PyQt is better or kivy. http://kivy.org/#home

**Comment by khalibartan** [comment]
@npcode2k14
